# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 167f487a9edbf5a14ea6a503280eb9fc334c15e695d11541e830c362e1ff2a10a09ff429ed9b3634a01741b14f9e7761ac9dff1aae857cbda62d8a90004f11f3

test:
  secret_key_base: 8fedb20d54cedf092f13577405501298bc801ae6105a9ace25fed926b20a335a68b51475e63c411ba09902ceb6ba367611b59bff32d6dabec7d9ce824aa56cf7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
